name: Run test on query-service

on:
  pull_request:
    branches:
      - develop
      - main
      - release/v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Confirm `go fmt` generates no diff
        run: |
          go fmt ./...
          git diff --exit-code
        shell: bash

      - name: Run go vet
        run: go vet ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Run tests
        run: go test ./pkg/query-service/...
